dataset_config = {
    'MUTAG': {
        'v-label': True,
        'e-label': True,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'BZR_MD': {
        'v-label': True,
        'e-label': True,
        'e-attr': True,
        'v-attr': False,
        'edge-standard': 'attr',
        'node-feat': 'label',
    },
    'PROTEINS': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': True,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'IMDB-BINARY': {
        'v-label': False,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'degeneracy',
        'node-feat': 'none',
    },
    'ER_MD': {
        'v-label': True,
        'e-label': True,
        'e-attr': True,
        'v-attr': False,
        'edge-standard': 'attr',
        'node-feat': 'label',
    },
    'REDDIT-BINARY': {
        'v-label': False,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'degeneracy',
        'node-feat': 'none',
    },
    'COX2_MD': {
        'v-label': True,
        'e-label': True,
        'e-attr': True,
        'v-attr': False,
        'edge-standard': 'attr',
        'node-feat': 'label',

    },
    'ENZYMES': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': True,
        'edge-standard': 'vattr',
        'node-feat': 'attr',
    },
    'PTC_MR': {
        'v-label': True,
        'e-label': True,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'PTC_FM': {
        'v-label': True,
        'e-label': True,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'PTC_FR': {
        'v-label': True,
        'e-label': True,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'PTC_MM': {
        'v-label': True,
        'e-label': True,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'NCI1': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'NCI109': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'IMDB-MULTI': {
        'v-label': False,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'degeneracy',
        'node-feat': 'none',
    },
    'REDDIT-MULTI-5K': {
        'v-label': False,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'degeneracy',
        'node-feat': 'none',
    },
    'DD': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    },
    'DHFR_MD': {
        'v-label': True,
        'e-label': True,
        'e-attr': True,
        'v-attr': False,
        'edge-standard': 'attr',
        'node-feat': 'label',
    },
    'COLLAB': {
        'v-label': False,
        'e-label': False,
        'e-attr': False,
        'v-attr': False,
        'edge-standard': 'degeneracy',
        'node-feat': 'none',
    },
    'BZR': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': True,
        'edge-standard': 'vattr',
        'node-feat': 'attr',
    },
    'COX2':{
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': True,
        'edge-standard': 'vattr',
        'node-feat': 'attr',
    },
    'DHFR': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': True,
        'edge-standard': 'vattr',
        'node-feat': 'attr',
    },
    'PROTEINS_full': {
        'v-label': True,
        'e-label': False,
        'e-attr': False,
        'v-attr': True,
        'edge-standard': 'curvature',
        'node-feat': 'label',
    }
}

